name = "Water Tank"
description = "Minimize surface area for given water mass."

[vars]
M   = "100 kg"
rho = "1000 kg/m^3"
A   = "m^2"
V   = "m^3"

[vectors.3]
d = ["m", "dimension vector"]

[model]
objective = "min: A"
constraints = [
  "A >= 2*(d[0]*d[1] + d[0]*d[2] + d[1]*d[2])",
  "V == d[0]*d[1]*d[2]",
  "M == V*rho",
]
